apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: NodePort
  ports:
  - name: tcp-port
    port: 8080
    targetPort: 20020
    nodePort: 31010
    protocol: TCP
  selector:
    app: echo-deployment