apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pp2-deploy1
  name: pp2-deploy13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pp2-deploy1
  template:
    metadata:
      labels:
        app: pp2-deploy1
    spec:
      containers:
      - env:
        - name: TCPPORT
          value: "12141"
        - name: PP_ENGINE_IP
          value: 10.97.137.229
        - name: WSPORT
          value: "12151"
        image: cregdva2renphubsvc0001.azurecr.io/echoserver:0.1.0
        imagePullPolicy: IfNotPresent
        name: pp2-deploy1
        ports:
        - containerPort: 12141
          protocol: TCP
        - containerPort: 12151
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
      nodeSelector:
        agentpool: npat00001
---
apiVersion: v1
kind: Service
metadata:
  name: pp-svc13
spec:
  ports:
  - name: tcp-port1-svc1
    port: 12141
    protocol: TCP
    targetPort: 12141
  - name: http-port1-svc1
    port: 12151
    protocol: TCP
    targetPort: 12151
  selector:
    app: pp2-deploy1
  type: LoadBalancer
