apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pp-deployment
  name: pp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pp-deployment
  template:
    metadata:
      labels:
        app: pp-deployment
    spec:
      containers:
      - name: pp-deployment
        image: cregdva2renphubsvc0001.azurecr.io/postprocessor-ws:0.1.3
        ports:
        - containerPort: 12131
          protocol: TCP
        - containerPort: 12101
          protocol: TCP
        env:
        - name: TCPPORT
          value: "12131"
        - name: PP_ENGINE_IP
          value: "192.168.56.3"
        - name: WSPORT
          value: "12101"
        resources:
          requests:
            memory: "512Mi"
            cpu: 0.5
          limits:
            memory: "512Mi"
            cpu: 0.5
      nodeSelector: 
        name: knode1