apiVersion: v1
kind: Service
metadata:
  name: pp-service
spec:
  type: NodePort
  ports:
  - name: tcp-port
    port: 8080
    targetPort: 12131
    nodePort: 30010
    protocol: TCP
  - name: webservice-port
    port: 80
    targetPort: 12101
    nodePort: 30020
    protocol: TCP
  selector:
    app: pp-deployment